flowerpotproject/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from flowerpotproject import settings
from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

admin.autodiscover()

urlpatterns = patterns('',

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^sorry/$', 'flowerpot.views.sorry'),
                       url(r'^signup/$', 'flowerpot.views.sign_up'),
                       url(r'^accounts/login/$', 'django.contrib.auth.views.login',
                           {'template_name': 'login.html'}),
                       url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
                           {'next_page': '/'}),

                       url(r'^remember_password/$', 'flowerpot.views.remember_password'),
                       url(r'^home/$', 'flowerpot.views.home'),
                       url(r'^$', 'flowerpot.views.home_page'),

                       url(r'^search/(?P<username>[a-zA-Z0-9_]+)/$', 'flowerpot.views.search'),


                       url(r'^profile/(?P<username>[a-zA-Z0-9_]+)/$', 'flowerpot.views.view_profile'),
                       url(r'^profile/about/(?P<username>[a-zA-Z0-9_]+)/$', 'flowerpot.views.view_about'),
                       url(r'^profile/followers/(?P<username>[a-zA-Z0-9_]+)/$', 'flowerpot.views.view_followers'),
                       url(r'^profile/followeds/(?P<username>[a-zA-Z0-9_]+)/$', 'flowerpot.views.view_followeds'),
                       url(r'^profile_edit/$', 'flowerpot.views.edit_profile'),

                       url(r'^messages/$', 'flowerpot.views.messages'),
                       url(r'^messages/detail/(?P<username>[a-zA-Z0-9_]+)/$', 'flowerpot.views.messages_detail'),

                       url(r'^group/(.+)/$', 'flowerpot.views.view_group'),
                       url(r'^leave/group/(?P<name>[a-zA-Z0-9_]+)/$', 'flowerpot.views.leave_group'),

                       url(r'^blog/new/$', 'flowerpot.views.new_blog'),
                       url(r'^blog/(?P<bid>[0-9]+)/$', 'flowerpot.views.view_blog'),
                       url(r'^blog/edit/(?P<bid>[0-9]+)/$', 'flowerpot.views.edit_blog'),
                       url(r'^blog/delete/(?P<bid>[0-9]+)/$', 'flowerpot.views.delete_blog'),


                       url(r'^status/delete/(?P<sid>[0-9]+)/$', 'flowerpot.views.delete_status'),
                       url(r'^group_status/delete/(?P<gsid>[0-9]+)/$', 'flowerpot.views.delete_group_status'),
                       url(r'^status_comment/delete/(?P<sid>[0-9]+)/$', 'flowerpot.views.delete_status_comment'),
                       url(r'^group_status_comment/delete/(?P<gsid>[0-9]+)/$',
                           'flowerpot.views.delete_group_status_comment'),


                       url(r'^add_followed/$', 'flowerpot.views.add_followed'),

                       ) + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flowerpot/models.py
# coding=utf-8
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Cities(models.Model):
    name = models.CharField(max_length=15, default='', null=False, blank=False)

    def __unicode__(self):
        return self.name


class ShareGroup(models.Model):
    name = models.CharField(max_length=250, null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True)


class UserAndShareGroup(models.Model):
    user = models.ForeignKey(User)
    share_group = models.ForeignKey(ShareGroup)


class UserDetails(models.Model):
    USER_TYPE = (
        (u'0', 'Obez'),
        (u'1', 'O Eskidendi'),
        (u'2', 'Saç Stilisti'),
        (u'3', 'Giyim Uzmanı'),
        (u'4', 'Diyetisyen'),
        (u'5', 'Giyim Firması'),
    )
    user = models.ForeignKey(User)
    type = models.CharField(max_length=1, choices=USER_TYPE, default='0')
    profile_photo = models.ImageField(null=True, blank=True, upload_to="profile_photos/")
    cover_photo = models.ImageField(null=True, blank=True, upload_to="cover_photos/")
    description = models.CharField(max_length=500, default='', null=False, blank=False)
    website = models.CharField(max_length=50, default='', null=True, blank=True)
    school = models.CharField(max_length=50, default='', null=False, blank=False)
    jobs = models.CharField(max_length=50, default='', null=False, blank=False)
    birthday = models.DateTimeField(null=True, blank=True)
    been = models.ForeignKey(Cities, related_name='bean', default=1)
    lives_in = models.ForeignKey(Cities, related_name='live_in', default=1)
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.user.username


class Follow(models.Model):
    follower = models.ForeignKey(User, related_name='follower')
    followed = models.ForeignKey(User, related_name='followed')
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.follower.username+', '+self.followed.username+"\'i takip ediyor"


class Message(models.Model):
    content = models.CharField(max_length=180, default='', null=True, blank=True)
    send = models.ForeignKey(User, related_name='send')
    to = models.ForeignKey(User, related_name='to')
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.send.username + ", " + self.to.username + " \'e Mesaj send" + "-" + str(self.date)


class Status(models.Model):
    STATUS_TYPE_CHOICES = (
        ('ST', 'Status'),
        ('WT', 'Weight')
    )
    content = models.CharField(max_length=180, default='', null=True, blank=True)
    type = models.CharField(max_length=2, choices=STATUS_TYPE_CHOICES, default='ST')
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)


class StatusPhotos(models.Model):
    photo = models.ImageField(null=True, blank=True, upload_to="status_photos/")
    status = models.ForeignKey(Status, default=1)
    date = models.DateTimeField(auto_now_add=True)


class StatusLike(models.Model):
    status = models.ForeignKey(Status)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)


class StatusComment(models.Model):
    content = models.CharField(max_length=250, null=False, blank=False)
    status = models.ForeignKey(Status)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)


class Blog(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False, default='blog yazısı')
    content = models.CharField(max_length=1000, null=False, blank=False)
    photo = models.ImageField(null=True, blank=True, upload_to="blog_photos/")
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)


class BlogLike(models.Model):
    blog = models.ForeignKey(Blog)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)


class BlogComment(models.Model):
    content = models.CharField(max_length=250, null=False, blank=False)
    blog = models.ForeignKey(Blog)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)


class ShareGroupStatus(models.Model):
    content = models.CharField(max_length=180, default='', null=True, blank=True)
    user = models.ForeignKey(User)
    share_group = models.ForeignKey(ShareGroup)
    date = models.DateTimeField(auto_now_add=True)


class ShareGroupStatusPhotos(models.Model):
    share_group_status = models.ForeignKey(ShareGroupStatus, default=1)
    photo = models.ImageField(null=True, blank=True, upload_to="group_status_photos/")
    date = models.DateTimeField(auto_now_add=True)


class ShareGroupStatusLike(models.Model):
    status = models.ForeignKey(ShareGroupStatus)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)


class ShareGroupStatusComment(models.Model):
    content = models.CharField(max_length=250, null=False, blank=False)
    group_status = models.ForeignKey(ShareGroupStatus)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)

templates/profile/followeds.html
{% extends "base.html" %}
{% load i18n %}
{% load tag %}
{% load staticfiles %}
{% block head_block %} {% endblock %}

{% block menu_block %}
{% endblock %}

{% block container_block %}
       <div class="container">
        <div class="cover profile">
            <div class="wrapper">
                <div class="image">
                    {% if user_detail.cover_photo %}
                        <img src="/media/{{ user_detail.cover_photo }}" alt="people" />
                    {% else %}
                        <img src="{% static 'images/profile-cover.jpg' %}" alt="people" />
                    {% endif %}
                </div>
                <ul class="friends">
                {% for follower in follower_list_cover %}
                    <li>
                        <a href="/profile/{{ follower.user.username }}/">
                            {% if follower.profile_photo == ''%}
                            <img src="{% static 'images/default-avatar.png' %}" alt="people" class="img-responsive" style="height: 83px !important;">
                            {% else %}
                            <img src="/media/{{ follower.profile_photo }}" alt="people" class="img-responsive" style="height: 83px !important;">
                            {% endif %}
                        </a>
                    </li>
                {% endfor %}
                    <li><a href="#" class="group"><i class="fa fa-group"></i></a>
                    </li>
                </ul>
            </div>
            <div class="cover-info">
                <div class="avatar">
                    {% if user_detail.profile_photo == '' %}
                        <img src="{% static 'images/default-avatar.png' %}" alt="people" class="img-responsive">
                    {% else %}
                        <img src="/media/{{ user_detail.profile_photo }}" alt="people" class="img-responsive">
                    {% endif %}
                </div>
                <div class="name">
                    <a href="/profile/{{ user.username }}/">
                {{ user.first_name }}
                {{ user.last_name }}
                {% if user_detail.type == '0' %}
                    ( Obez )
                {% elif user_detail.type == '1' %}
                    ( O Eskidendi )
                {% elif user_detail.type == '2' %}
                    ( Saç Stilisti )
                {% elif user_detail.type == '3' %}
                    ( Giyim Uzmanı )
                {% elif user_detail.type == '4' %}
                    ( Diyetisyen )
                {% elif user_detail.type == '5' %}
                    ( Giyim Firması )
                {% endif %}
            </a>
                </div>
                <ul class="cover-nav">
                    <li><a href="/profile/{{ user.username }}/"><i class="fa fa-fw icon-ship-wheel"></i> Profil</a>
                    </li>
                    <li><a href="/profile/about/{{ user.username }}/"><i class="fa fa-fw icon-user-1"></i> Hakkında</a>
                    </li>
                    <li><a href="/profile/followers/{{ user.username }}/"><i class="fa fa-fw fa-users"></i> Takipçiler</a>
                    </li>
                    <li><a href="/profile/followeds/{{ user.username }}/"><i class="fa fa-fw fa-users"></i> Takip Ettikleri</a>
                    </li>
                    {% if request.user != user %}
                    <li><a href="javascript:void(0)" id="{{ user.id }}" onclick="added_ticket_to_my_bag(this);"><i class="fa fa-fw fa-check-circle"></i>
                        <output id="o{{ user.id }}">{% if is_followed_by_me %}{{ follow_status.1 }}{% else %}{{ follow_status.0 }}{% endif %}</output>
                    </a>
                    <li><a href="/messages/detail/{{ username }}"><i class="fa fa-fw fa-envelope"></i> Mesaj Gönder</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <div class="timeline row" data-toggle="gridalicious">
            {% if all_follower_list %}
            {% for follower in all_follower_list %}
            <div class="timeline-block">
                <div class="panel panel-default user-box">
                    <div class="panel-body">
                        <div class="media">
                            {% if follower.0.profile_photo == '' %}
                            <img src="{% static 'images/default-avatar.png' %}" style="width: 80px !important;height: 80px !important;" alt="people" class="media-object img-circle pull-left" />
                            {% else %}
                            <img src="/media/{{ follower.0.profile_photo }}" style="width: 80px !important;height: 80px !important;" alt="people" class="media-object img-circle pull-left" />
                            {% endif %}
                            <div class="media-body">
                                <a href="/profile/{{ follower.0.user.username }}/" class="username">{{ follower.0.user.username }} {% if user_detail.type == '0' %}
                    ( Obez )
                {% elif follower.0.type == '1' %}
                    ( O Eskidendi )
                {% elif follower.0.type == '2' %}
                    ( Saç Stilisti )
                {% elif follower.0.type == '3' %}
                    ( Giyim Uzmanı )
                {% elif follower.0.type == '4' %}
                    ( Diyetisyen )
                {% elif follower.0.type == '5' %}
                    ( Giyim Firması )
                {% endif %}</a></a>
                                <div class="profile-icons">
                                    <span><i class="fa fa-users"></i> {{ follower.3 }}</span> <span><i class="fa fa-photo"></i> {{ follower.2 }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if follower.1 %}
                    <div class="panel-body bordered">
                        <p class="common-friends">Takipçiler</p>
                        <div class="user-friend-list">
                            {%  for follow in follower.1 %}
                            <a href="/profile/{{ follow.user.username }}/">
                                {% if follow.profile_photo == '' %}
                                <img src="{% static 'images/default-avatar.png' %}" style="width: 50px !important;height: 50px !important;" alt="{{ follow.user.username }}" class="img-circle" />
                                {% else %}
                                <img src="/media/{{ follow.profile_photo }}" style="width: 50px !important;height: 50px !important;" alt="{{ follow.user.username }}" class="img-circle" />
                                {% endif %}
                            </a>
                                {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                    <div class="panel-footer">
                        <a href="javascript:void(0)" id="{{ follower.0.user.id }}" onclick="added_ticket_to_my_bag(this);" class="btn btn-default btn-sm">
                            <output id="o{{ follower.0.user.id }}">
                                {% if follower.4 %}
                                {{ follow_status.1 }}
                                {% else %}
                                {{ follow_status.0 }}
                                {% endif %}
                            </output>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
                <p style="text-align: center">Henüz takip edettiği kişi bulunmuyor !</p>
            {% endif %}
        </div>
    </div>

{% endblock %}
{% block script_block %}
    <script type="text/javascript">
        function added_ticket_to_my_bag(followed) {
            $.ajax({
                type: "POST",
                url: "/add_followed/",
                data: {followed: + followed.id },
                success: okey(followed),
                dataType: JSON
            });
        }
        function okey(followed)
        {
            console.log('geldi tipini siktiğin');
            var out = $("#o"+followed.id).html();
            if (out == "{{ follow_status.0 }}"){
            $("#o"+followed.id).html("{{ follow_status.1 }}");
            }else{
            $("#o"+followed.id).html("{{ follow_status.0 }}");
            }
        }
</script>
{% endblock %}

templates/profile/profile_edit.html
{% extends "base.html" %}
{% load i18n %}
{% load tag %}
{% load staticfiles %}

{% block head_block %} {% endblock %}

{% block menu_block %}
{% endblock %}

{% block container_block %}

<div class="panel-body">
    {% if form_user.errors %}
        {{ form_user.errors }}
    {% endif %}
        <form class="form-horizontal" id="form_user" method='POST' >
            {% csrf_token %}

            <div class="col-sm-12">
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">İsim :</label>
                    <div class="col-sm-5    ">
                        {{ form_user.first_name|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">Soyisim :</label>
                    <div class="col-sm-5">
                        {{ form_user.last_name|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">Kullanıcı Adı :</label>
                    <div class="col-sm-5">
                        {{ form_user.username|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">Mail :</label>
                    <div class="col-sm-5">
                        {{ form_user.email|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">Parola :</label>
                    <div class="col-sm-5">
                        {{ form_user.password|add_class:"form-control"}}
                    </div>
                </div>
                {{ form_user.last_login }}
                {{ form_user.is_active }}
                {{ form_user.date_joined }}
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-3">
                        <button type="submit" name="form_user" class="btn btn-default btn-block">Düzenle</button>
                    </div>
                </div>
            </div>
            {% if next %}
                <input type="hidden" name="next" value="{{ next }}">
            {% else %}
                <input type="hidden" name="next" value="/">
            {% endif %}
        </form>
</div>
    <hr/>
    <hr/>
<div class="panel-body">
    {% if form_user_detail.errors %}
        {{ form_user_detail.errors }}
    {% endif %}
        <form class="form-horizontal" id="form_user_detail" method='POST' enctype="multipart/form-data" >
            {% csrf_token %}

            <div class="col-sm-12">
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">Profil Fotoğrafı :</label>
                    <div class="col-sm-5 ">
                        {{ form_user_detail.profile_photo|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">Kapak Resimi :</label>
                    <div class="col-sm-5">
                        {{ form_user_detail.cover_photo|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">Hakkında :</label>
                    <div class="col-sm-5">
                        {{ form_user_detail.description|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">Website :</label>
                    <div class="col-sm-5    ">
                        {{ form_user_detail.website|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">Okul :</label>
                    <div class="col-sm-5">
                        {{ form_user_detail.school|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">İş :</label>
                    <div class="col-sm-5">
                        {{ form_user_detail.jobs|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">Doğum Tarihi :</label>
                    <div class="col-sm-5    ">
                            <input id="id_birthday" name="birthday" type="date" class="form-control"> Şu an:  {{ user_detail.birthday|date }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">Memleketi :</label>
                    <div class="col-sm-5">
                        {{ form_user_detail.been|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">Yaşadığı Yer :</label>
                    <div class="col-sm-5">
                        {{ form_user_detail.lives_in|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="input1" class="col-sm-3 control-label">Kullanıcı Tipi :</label>
                    <div class="col-sm-5">
                        {{ form_user_detail.type|add_class:"form-control" }}
                    </div>
                </div>
                {{ form_user_detail.user }}
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-3">
                        <button type="submit" name="form_user_detail" class="btn btn-default btn-block">Düzenle</button>
                    </div>
                </div>
            </div>
            {% if next %}
                <input type="hidden" name="next" value="{{ next }}">
            {% else %}
                <input type="hidden" name="next" value="/">
            {% endif %}
        </form>
</div>
    <div class="clearfix" style="height: 50px"></div>

{% endblock %}
{% block script_block %}
    <script type="text/javascript">
  $(function() {
    $('#datetimepicker1').datetimepicker({
      language: 'tr-TR'
    });
  });
</script>
{% endblock %}